using UnityEngine;
using UnityEngine.InputSystem;


namespace RPGGame
{
    [DefaultExecutionOrder(-1)]
    public class InputManager : MonoBehaviour
    {
        public static Vector2 Movement { get; private set; } = Vector2.zero;
        public static bool IsJump { get; private set; } = false;

        private InputAction _moveAction;
        private InputAction _jumpAction;

        private void Awake()
        {
            if (_moveAction == null)
            {
                _moveAction = InputSystem.actions.FindAction("Move");
            }

            if (_jumpAction == null)
            {
                _jumpAction = InputSystem.actions.FindAction("Jump");
            }
        }

        private void Update()
        {
            Movement = _moveAction.ReadValue<Vector2>();
            IsJump = _jumpAction.WasPressedThisFrame();
        }
    }
}